#!/bin/bash

opt=$(echo -e "0. Exit
1. Upload screenshot
" | rofi -dmenu)
dbg=$1

MDebug() {
    if [[ $dbg == "--debug" ]]; then
        echo $1
    fi
}

if [[ ${opt::1} == 0 ]]; then
    MDebug "Received exit"
    exit 0
elif [[ ${opt::1} == 1 ]]; then
    MDebug "Received 1"
    limf -l ~/shot.png | xclip -sel clip
fi
